import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Projekt Kshitij | kshvbgde",
  description:
    "Generated by create next appEnhance your reading with Kshitij, an open-source article summarizer that transforms lengthy articles into concise summaries using the powerful GPT-4.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-background`}>
        {children}

        <Footer />
      </body>
    </html>
  );
}
